stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - pytest

build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  script:
    - docker build -t shopdemo-monolith .

deploy:
  stage: deploy
  script:
    - echo "Déploiement de l'application monolithique"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
